//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetterBot.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class get_messages
    {
        public int id { get; set; }
        public Nullable<int> get_type_id { get; set; }
        public string get_message { get; set; }
        public Nullable<bool> gm_enabled { get; set; }
    
        public virtual get_type get_type { get; set; }
    }
}
