//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetterBot.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class most_getted_weekday
    {
        public string get_weekday { get; set; }
        public Nullable<int> wd_count { get; set; }
    }
}
