//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetterBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class botget
    {
        public int messageid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<System.DateTime> get_date { get; set; }
        public Nullable<int> get_seconds { get; set; }
        public string get_weekday { get; set; }
        public Nullable<int> get_type_id { get; set; }
    
        public virtual get_type get_type { get; set; }
        public virtual user user { get; set; }
    }
}
