//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetterBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class get_type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public get_type()
        {
            this.botgets = new HashSet<botget>();
        }
    
        public int id { get; set; }
        public string get_type_name { get; set; }
        public Nullable<int> get_type_hour { get; set; }
        public Nullable<int> get_type_minute { get; set; }
        public Nullable<bool> get_enabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<botget> botgets { get; set; }
    }
}
